// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoInstallBinaries() {
  return window['go']['main']['App']['AutoInstallBinaries']();
}

export function CheckUpdateStatus() {
  return window['go']['main']['App']['CheckUpdateStatus']();
}

export function GetHardware() {
  return window['go']['main']['App']['GetHardware']();
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function InstallLocalBinaries(arg1) {
  return window['go']['main']['App']['InstallLocalBinaries'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function RunBench() {
  return window['go']['main']['App']['RunBench']();
}

export function RunMultimodalCLI() {
  return window['go']['main']['App']['RunMultimodalCLI']();
}

export function RunQuantize() {
  return window['go']['main']['App']['RunQuantize']();
}

export function RunRPC() {
  return window['go']['main']['App']['RunRPC']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartLlama(arg1, arg2) {
  return window['go']['main']['App']['StartLlama'](arg1, arg2);
}

export function StopLlama() {
  return window['go']['main']['App']['StopLlama']();
}
